name: Laravel

on:
  push:
  pull_request:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer:v2
        coverage: xdebug
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Set up MySQL
      env:
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_DATABASE: lara2
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }} 
    - name: Shop app install
      run: php artisan shop:install
    - name: npm
      run: npm run dev
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_PASSWORD: root
      run: vendor/bin/phpunit
